### ISSUE TITLE
Threshold Cooling/Heating Temperature was supplied an illegal value

### ISSUE THREAD

**Issue by 1homebridge** [codyc1515/homebridge-panasonic-air-conditioner#73]
I keep getting these error logs that the heating threshold temperature value was supplied an illegal value 10 and the cooling threshold temperature value was supplied an illegal value 0 all of a sudden since yesterday without me having changed anything.
Can anyone help or advise?
Thanks

**Comment by guwo65** [comment]
I had the Same Problem today and a Bit more, so i made the Changes written By putthegundownkinkade in #70 and by CharlesMonneron in #65.
And it  Works . No more Warnung and errors.
Thx to both!!!
My homebridge is Running in docker on QNAP.

**Comment by veitch123** [comment]
> I had the Same Problem today and a Bit more, so i made the Changes written By putthegundownkinkade in #70 and by CharlesMonneron in #65.
> And it Works . No more Warnung and errors.
> Thx to both!!!
> My homebridge is Running in docker on QNAP.

How did you make those changes? I hate the errors.

**Comment by guwo65** [comment]
First of all, I am not a programmer. My knowledge is very rudimentary.
 I located index.js on my NAS(QNAP) in Container/homebridge/node_modules/homebridge-panasonic-air-conditioner.
Then I made a backup of this file!
I opened index.js with TextEdit on my QNAP.
I increased the version number by 1 (--->const APP_VERSION = "1.13.0";)
Then I first made the change in line 300 ( .OFF--->.COOL)
Then I made the change to line 244 with copy+paste
I saved the index.js and restarted home bridge.

I hope it will work for you too.

**Comment by veitch123** [comment]
Hmm. Bit beyond me alas. I tried using terminal but couldn't even get the file to come across. 
I tried putting the SD card in my Mac and it seemed I needed to mount directories which I couldn't do. 

I'm really really hoping the dev releases a new version that includes these changes.

**Comment by codyc1515** [comment]
Fixed.

**Comment by xyz667** [comment]
I still get these warnings:

> This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 10 exceeded minimum of 16.

For every device 2 warnings upon Homebridge start (1 for Cooling, 1 for Warming Threshold Temperature).

**Comment by codyc1515** [comment]
Yes this is not possible to fix currently. The bug is due to HAP-NodeJS.
